
server:
    port: 10000
spring:
    application:
        name: abz-gataway
    cloud:
        gateway:
            routes:
                # =====================================
                - id: abz-business
                  uri: lb://abz-business
                  order: 10000
                  predicates:
                      - Path=/business/**
                  filters:
                      - StripPrefix=1
                - id: abz-account
                  uri: lb://abz-account
                  order: 10000
                  predicates:
                      - Path=/account/**
                  filters:
                      - StripPrefix=1
                - id: abz-oauth
                  uri: lb://abz-oauth
                  order: 10000
                  predicates:
                      - Path=/oauth/**
                  filters:
                      - StripPrefix=1
                - id: abz-order
                  uri: lb://abz-order
                  order: 10000
                  predicates:
                      - Path=/order/**
                  filters:
                      - StripPrefix=1
                - id: abz-storage
                  uri: lb://abz-storage
                  order: 10000
                  predicates:
                      - Path=/storage/**
                  filters:
                      - StripPrefix=1
            discovery:
                locator:
                    enabled: true
                    lower-case-service-id: true
